# Docker Compose configuration with BuildKit caching for Conductor workspaces
# This provides shared caching across all Conductor workspaces

# Usage:
# 1. Export COMPOSE_FILE to include this file:
#    export COMPOSE_FILE=docker-compose.yml:docker-compose.buildkit.yml
# 2. Or use it directly:
#    docker compose -f docker-compose.yml -f docker-compose.buildkit.yml up

services:
  # Extend the existing services to add shared cache volumes
  adcp-server:
    volumes:
      # Add shared pip/uv cache volume
      - adcp_global_pip_cache:/root/.cache/pip
      - adcp_global_uv_cache:/cache/uv
      - ./audit_logs:/app/audit_logs

  admin-ui:
    volumes:
      # Add shared pip/uv cache volume
      - adcp_global_pip_cache:/root/.cache/pip
      - adcp_global_uv_cache:/cache/uv
      - ./audit_logs:/app/audit_logs

# Define shared cache volumes that persist across all workspaces
volumes:
  adcp_global_pip_cache:
    external: true
  adcp_global_uv_cache:
    external: true