"""``message`` reaches an A2A buyer as a declared field, not as a transport stamp.

This suite was written against handlers that reached for ``response.message`` on
response types that had no such attribute, and against the A2A serializer that
compensated by WRITING one in. Both halves are gone:

* ``message`` is a declared field on every response model —
  ``core/protocol-envelope.json`` defines it ("Human-readable summary of the task
  result ... Generated by the protocol layer") and every response inherits
  ``adcp.types.ProtocolEnvelope``. The implementation fills it. There is no
  response type it can be missing from, so there is no AttributeError left to
  prevent; what is left to grade is that the value the implementation set is the
  value that reaches the body.
* ``_stamp_a2a_protocol_fields`` is deleted. A2A's serializer is
  ``src/core/tools/_wire.py::to_wire``, which is ``model_dump(mode="json")`` and
  nothing else, and MCP and REST call the same function. So these tests assert
  through ``to_wire`` — the function that actually produces the bytes — rather than
  through a hand-built dict that could agree with nothing.

``success`` is not asserted anywhere here because it no longer exists: A2A used to
derive it from ``errors`` and write it into every payload, a key AdCP declares on no
response schema of our fourteen tools.

Key principle, unchanged: test the ACTUAL serialization on A2A's request path
(``AdCPRequestHandler._dispatch_skill`` and the ``to_wire`` it ends in), not the
response object in isolation. The eleven per-tool ``_handle_<tool>_skill`` methods
this file was written against are gone: A2A dispatch is one derived method, and a
tool is dispatchable because ``TOOLS[name].a2a`` is True.

Regression prevention: https://github.com/prebid/salesagent/pull/337
"""

from unittest.mock import MagicMock, patch

import pytest

from src.a2a_server.adcp_a2a_server import AdCPRequestHandler
from tests.factories.principal import PrincipalFactory

pytestmark = [pytest.mark.integration, pytest.mark.requires_db]

_MOCK_IDENTITY = PrincipalFactory.make_identity(
    principal_id="test_principal",
    tenant_id="test_tenant",
    tenant={"tenant_id": "test_tenant"},
    protocol="a2a",
)


@pytest.mark.integration
class TestA2AMessageFieldValidation:
    """A2A's serializer carries the implementation's ``message`` through, unaltered."""

    @pytest.fixture
    def handler(self):
        """Create A2A request handler."""
        return AdCPRequestHandler()

    def test_the_a2a_stamp_adds_message_to_any_response(self):
        """``message`` reaches the wire for every skill, graded once on the step that carries it.

        Five per-tool copies of this stood here -- create_media_buy, sync_creatives,
        get_products, list_creatives, list_creative_formats -- each driving a real skill
        through full setup to ask whether its reply carried a ``message``. They could not
        disagree then and cannot now: ONE function serializes every A2A response, and
        since ``4cba8d080`` it is ``to_wire``, shared with MCP and REST. Five tools cannot
        answer that question differently, so asking five times graded the same function
        five times at five times the cost -- the per-tool enumeration the registry
        replaced everywhere else.

        There is no stamp left to grade. ``_stamp_a2a_protocol_fields`` overwrote
        ``message`` with ``str(response)``; ``to_wire`` adds nothing, so the obligation
        that survives is TRANSPARENCY -- the field the implementation set is the field on
        the wire, byte for byte, and it is not silently dropped by ``exclude_none`` or
        replaced by a repr. Asserting equality with the value set is what says that; a
        bare ``"message" in body`` would pass on a stamp that threw the real value away.
        The deleted ``success`` is asserted absent for the same reason: its removal is
        the behavior, so something has to fail if it comes back.

        That the serialized value then reaches the artifact is pinned separately, by
        test_a2a_skill_invocation.py::test_artifact_text_part_is_the_data_part_message.
        """
        from src.core.schemas import GetProductsResponse
        from src.core.tools._wire import to_wire

        summary = "Found 0 products."
        body = to_wire(GetProductsResponse(products=[], message=summary))

        assert body["message"] == summary, "to_wire must carry the implementation's message through verbatim"
        assert "success" not in body, "success is deleted; AdCP declares it on no tool response"


@pytest.mark.integration
class TestA2AResponseDictConstruction:
    """Every response type serializes to a body that carries its own ``message``.

    These used to hand-build the dict A2A was believed to send (``{"success": ...,
    "message": str(response)}``) and assert on that hand-built dict, which could
    agree with production only by coincidence. They now call ``to_wire``, the
    function that produces the real bytes, so a change to what A2A sends fails
    here instead of passing against a local copy of the old idea.
    """

    def test_create_media_buy_response_to_dict(self):
        """CreateMediaBuySuccess serializes with the message the caller set.

        NOTE: CreateMediaBuyResponse is a Union type (Success | Error), so the
        Success variant is what carries a media_buy_id to talk about.
        """
        from src.core.schemas import CreateMediaBuySuccess
        from src.core.tools._wire import to_wire

        response = CreateMediaBuySuccess.carrier(
            media_buy_id="mb-456",
            packages=[],
            message="Media buy mb-456 created successfully.",
        )

        body = to_wire(response)

        assert body["media_buy_id"] == "mb-456"
        assert body["message"] == "Media buy mb-456 created successfully."
        assert "success" not in body

    def test_sync_creatives_response_to_dict(self):
        """SyncCreativesResponse serializes with the message the caller set."""
        from src.core.schemas import SyncCreativeResult, SyncCreativesResponse
        from src.core.tools._wire import to_wire

        response = SyncCreativesResponse(
            dry_run=False,
            creatives=[
                SyncCreativeResult(
                    creative_id="cr-001",
                    internal_status="approved",
                    action="created",  # Required field
                )
            ],
            message="Synced 1 creative.",
        )

        body = to_wire(response)

        assert body["message"] == "Synced 1 creative."
        assert "success" not in body

    def test_get_products_response_to_dict(self):
        """GetProductsResponse serializes with the message the caller set.

        Also pins the shape of the payload beside it: ``products`` is serialized by the
        same dump, so nothing has to walk the list and call ``model_dump`` per item the
        way the hand-built dict this replaces did.
        """
        from src.core.schemas import GetProductsResponse
        from src.core.tools._wire import to_wire

        response = GetProductsResponse(products=[], message="No products matched your requirements.")

        body = to_wire(response)

        assert body["message"] == "No products matched your requirements."
        assert body["products"] == []
        assert "success" not in body

    def test_all_response_types_declare_message(self):
        """Every enveloped response type declares ``message``, so none can lack it.

        The contract this replaces was "``__str__`` OR ``.message``", which the
        ``__str__`` half made unfalsifiable — every Python object has one. ``message``
        is declared by ``adcp.types.ProtocolEnvelope``, so the honest form of the check
        is the field plus the inheritance that supplies it. What it catches is a
        response type added outside that inheritance: the transports read the field and
        nothing else, so such a type would reach a buyer with no summary at all.

        ``CreateMediaBuyError`` is deliberately not in the list. Measured against the
        pin, it is not a ``ProtocolEnvelope`` at all — the create-media-buy error branch
        declares ``errors``/``context``/``ext`` and no ``message``, which is why
        ``to_wire`` is bound to ``ProtocolEnvelope`` rather than ``BaseModel``. Asserting
        a ``message`` on it would state the opposite of the pinned schema. Its exclusion
        is asserted rather than merely commented, so the day the SDK gives that branch an
        envelope, this stops being an exception silently.
        """
        from adcp.types import ProtocolEnvelope

        from src.core.schemas import (
            CreateMediaBuyError,
            CreateMediaBuySuccess,
            GetProductsResponse,
            ListCreativeFormatsResponse,
            ListCreativesResponse,
            SyncCreativesResponse,
        )

        response_types = [
            CreateMediaBuySuccess,
            SyncCreativesResponse,
            GetProductsResponse,
            ListCreativeFormatsResponse,
            ListCreativesResponse,
        ]

        for response_cls in response_types:
            assert issubclass(response_cls, ProtocolEnvelope), (
                f"{response_cls.__name__} does not inherit ProtocolEnvelope — to_wire's bound refuses it"
            )
            assert "message" in response_cls.model_fields, (
                f"{response_cls.__name__} inherits ProtocolEnvelope but declares no `message`"
            )

        assert not issubclass(CreateMediaBuyError, ProtocolEnvelope), (
            "CreateMediaBuyError gained a protocol envelope — it can carry a `message` now, "
            "so it belongs in the list above rather than in this exception"
        )


@pytest.mark.integration
class TestA2AErrorHandling:
    """Test that A2A handlers properly handle errors without AttributeErrors."""

    @pytest.fixture
    def handler(self):
        return AdCPRequestHandler()

    @pytest.mark.asyncio
    async def test_skill_error_has_message_field(self, handler, sample_principal):
        """Test that skill errors return proper message fields."""
        handler._get_auth_token = MagicMock(return_value=sample_principal["access_token"])

        with patch("src.core.resolved_identity.resolve_identity", return_value=_MOCK_IDENTITY):
            # Force an error by passing invalid parameters
            params = {
                # Missing required fields - should cause validation error
            }

            try:
                # _dispatch_skill IS A2A's whole request path: validate the parameter bag into
                # the registry row's DTO, invoke_tool, then _serialize_for_a2a. It returns the
                # serialized dict, so there is nothing left to serialize here.
                result = await handler._dispatch_skill("create_media_buy", params, identity=_MOCK_IDENTITY)
                # If it doesn't raise, the failure has to be readable from the body itself.
                # `success` is gone, so `errors` IS the signal a buyer reads — the same
                # field A2A used to derive `success` from before writing it in.
                if result.get("errors"):
                    assert result.get("message") or result.get("adcp_error"), (
                        "an errored body must say what went wrong, on `message` or `adcp_error`"
                    )
            except Exception as e:
                pass  # the operation must raise; its message is not asserted
                # Errors are expected for invalid params
