# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_error_json.json
#   source_etag: W/"68efb338-3d7"
#   source_last_modified: Wed, 15 Oct 2025 14:44:08 GMT

from __future__ import annotations

from typing import Annotated, Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Error code for programmatic handling")]
    message: Annotated[str, Field(description="Human-readable error message")]
    field: Annotated[
        Optional[str], Field(description="Field path associated with the error (e.g., 'packages[0].targeting')")
    ] = None
    suggestion: Annotated[Optional[str], Field(description="Suggested fix for the error")] = None
    retry_after: Annotated[
        Optional[float], Field(description="Seconds to wait before retrying the operation", ge=0.0)
    ] = None
    details: Annotated[Optional[Any], Field(description="Additional task-specific error details")] = None
