# generated by datamodel-codegen:
#   filename:  _schemas_v1_standard-formats_index_json.json
#   source_etag: W/"68f2761a-248c"
#   source_last_modified: Fri, 17 Oct 2025 17:00:10 GMT

from __future__ import annotations

from typing import Annotated, Any

from pydantic import Field, RootModel


class AdcpStandardCreativeFormatsRegistry(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description="Authoritative registry of standard creative formats for Ad Context Protocol",
            title="AdCP Standard Creative Formats Registry",
        ),
    ]
