# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_pricing-model_json.json
#   source_etag: W/"68ee6f3c-339"
#   source_last_modified: Tue, 14 Oct 2025 15:41:48 GMT

from __future__ import annotations

from enum import Enum


class PricingModel(Enum):
    cpm = "cpm"
    vcpm = "vcpm"
    cpc = "cpc"
    cpcv = "cpcv"
    cpv = "cpv"
    cpp = "cpp"
    flat_rate = "flat_rate"
