# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_delivery-type_json.json
#   schema_hash: c4747767e14c

from __future__ import annotations

from enum import Enum


class DeliveryType(Enum):
    guaranteed = "guaranteed"
    non_guaranteed = "non_guaranteed"
