# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_activation-key_json.json
#   schema_hash: 9e4da357a99f

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ActivationKey1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[Literal["segment_id"], Field(description="Segment ID based targeting")]
    segment_id: Annotated[
        str, Field(description="The platform-specific segment identifier to use in campaign targeting")
    ]


class ActivationKey2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[Literal["key_value"], Field(description="Key-value pair based targeting")]
    key: Annotated[str, Field(description="The targeting parameter key")]
    value: Annotated[str, Field(description="The targeting parameter value")]


class ActivationKey(RootModel[ActivationKey1 | ActivationKey2]):
    root: Annotated[
        ActivationKey1 | ActivationKey2,
        Field(
            description="Universal identifier for using a signal on a destination platform. Can be either a segment ID or a key-value pair depending on the platform's targeting mechanism.",
            title="Activation Key",
        ),
    ]
