# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_channels_json.json
#   source_etag: W/"68f2761a-16b"
#   source_last_modified: Fri, 17 Oct 2025 17:00:10 GMT

from __future__ import annotations

from enum import Enum


class AdvertisingChannels(Enum):
    display = "display"
    video = "video"
    audio = "audio"
    native = "native"
    dooh = "dooh"
    ctv = "ctv"
    podcast = "podcast"
    retail = "retail"
    social = "social"
