# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_package-status_json.json
#   source_etag: W/"68ee6f3c-1c4"
#   source_last_modified: Tue, 14 Oct 2025 15:41:48 GMT

from __future__ import annotations

from enum import Enum


class PackageStatus(Enum):
    draft = "draft"
    active = "active"
    paused = "paused"
    completed = "completed"
