# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_pacing_json.json
#   schema_hash: d510c0568e15

from __future__ import annotations

from enum import Enum


class Pacing(Enum):
    even = "even"
    asap = "asap"
    front_loaded = "front_loaded"
