# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_frequency-cap-scope_json.json
#   schema_hash: 14ebfd2c8b6e

from __future__ import annotations

from enum import Enum


class FrequencyCapScope(Enum):
    package = "package"
