# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_task-type_json.json
#   source_etag: W/"68ffaa97-531"
#   source_last_modified: Mon, 27 Oct 2025 17:23:35 GMT

from __future__ import annotations

from enum import Enum


class TaskType(Enum):
    create_media_buy = "create_media_buy"
    update_media_buy = "update_media_buy"
    sync_creatives = "sync_creatives"
    activate_signal = "activate_signal"
    get_signals = "get_signals"
