# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_publisher-identifier-types_json.json
#   schema_hash: 3074cb2fcde8

from __future__ import annotations

from enum import Enum


class PublisherIdentifierTypes(Enum):
    tag_id = "tag_id"
    duns = "duns"
    lei = "lei"
    seller_id = "seller_id"
    gln = "gln"
