# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_delivery-type_json.json
#   source_etag: W/"68f9296c-1a0"
#   source_last_modified: Wed, 22 Oct 2025 18:58:52 GMT

from __future__ import annotations

from enum import Enum


class DeliveryType(Enum):
    guaranteed = "guaranteed"
    non_guaranteed = "non_guaranteed"
