# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_pricing-model_json.json
#   timestamp: 2025-10-17T17:36:06+00:00

from __future__ import annotations

from enum import Enum


class PricingModel(Enum):
    cpm = "cpm"
    vcpm = "vcpm"
    cpc = "cpc"
    cpcv = "cpcv"
    cpv = "cpv"
    cpp = "cpp"
    flat_rate = "flat_rate"
