# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_start-timing_json.json
#   source_etag: W/"68f9296c-1da"
#   source_last_modified: Wed, 22 Oct 2025 18:58:52 GMT

from __future__ import annotations

from typing import Annotated, Union

from pydantic import AwareDatetime, Field, RootModel


class StartTiming(RootModel[Union[str, AwareDatetime]]):
    root: Annotated[
        Union[str, AwareDatetime],
        Field(description="Campaign start timing: 'asap' or ISO 8601 date-time", title="Start Timing"),
    ]
