# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_list-creatives-response_json.json
#   source_etag: W/"68ee6f3c-367c"
#   source_last_modified: Tue, 14 Oct 2025 15:41:48 GMT

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal, Optional, Union

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class Direction(Enum):
    asc = "asc"
    desc = "desc"


class SortApplied(BaseModel):
    field: Optional[str] = None
    direction: Optional[Direction] = None


class QuerySummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total_matching: Annotated[
        int, Field(description="Total number of creatives matching filters (across all pages)", ge=0)
    ]
    returned: Annotated[int, Field(description="Number of creatives returned in this response", ge=0)]
    filters_applied: Annotated[
        Optional[list[str]], Field(description="List of filters that were applied to the query")
    ] = None
    sort_applied: Annotated[Optional[SortApplied], Field(description="Sort order that was applied")] = None


class Pagination(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    limit: Annotated[int, Field(description="Maximum number of results requested", ge=1)]
    offset: Annotated[int, Field(description="Number of results skipped", ge=0)]
    has_more: Annotated[bool, Field(description="Whether more results are available")]
    total_pages: Annotated[Optional[int], Field(description="Total number of pages available", ge=0)] = None
    current_page: Annotated[Optional[int], Field(description="Current page number (1-based)", ge=1)] = None


class FormatId(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent_url: Annotated[
        AnyUrl,
        Field(
            description="URL of the agent that defines this format (e.g., 'https://creatives.adcontextprotocol.org' for standard formats, or 'https://publisher.com/.well-known/adcp/sales' for custom formats)"
        ),
    ]
    id: Annotated[
        str,
        Field(
            description="Format identifier within the agent's namespace (e.g., 'display_300x250', 'video_standard_30s')",
            pattern="^[a-zA-Z0-9_-]+$",
        ),
    ]


class Status(Enum):
    processing = "processing"
    approved = "approved"
    rejected = "rejected"
    pending_review = "pending_review"


class Assets(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["image"]
    url: Annotated[AnyUrl, Field(description="URL to the image asset")]
    width: Annotated[Optional[int], Field(description="Image width in pixels", ge=1)] = None
    height: Annotated[Optional[int], Field(description="Image height in pixels", ge=1)] = None
    format: Annotated[Optional[str], Field(description="Image file format (jpg, png, gif, webp, etc.)")] = None
    alt_text: Annotated[Optional[str], Field(description="Alternative text for accessibility")] = None


class Assets38(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["video"]
    url: Annotated[AnyUrl, Field(description="URL to the video asset")]
    width: Annotated[Optional[int], Field(description="Video width in pixels", ge=1)] = None
    height: Annotated[Optional[int], Field(description="Video height in pixels", ge=1)] = None
    duration_ms: Annotated[Optional[int], Field(description="Video duration in milliseconds", ge=0)] = None
    format: Annotated[Optional[str], Field(description="Video file format (mp4, webm, mov, etc.)")] = None
    bitrate_kbps: Annotated[Optional[int], Field(description="Video bitrate in kilobits per second", ge=1)] = None


class Assets39(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["audio"]
    url: Annotated[AnyUrl, Field(description="URL to the audio asset")]
    duration_ms: Annotated[Optional[int], Field(description="Audio duration in milliseconds", ge=0)] = None
    format: Annotated[Optional[str], Field(description="Audio file format (mp3, wav, aac, etc.)")] = None
    bitrate_kbps: Annotated[Optional[int], Field(description="Audio bitrate in kilobits per second", ge=1)] = None


class Assets40(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["text"]
    content: Annotated[str, Field(description="Text content")]
    max_length: Annotated[Optional[int], Field(description="Maximum character length constraint", ge=1)] = None
    language: Annotated[Optional[str], Field(description="Language code (e.g., 'en', 'es', 'fr')")] = None


class Assets41(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["html"]
    content: Annotated[str, Field(description="HTML content")]
    version: Annotated[Optional[str], Field(description="HTML version (e.g., 'HTML5')")] = None


class Assets42(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["css"]
    content: Annotated[str, Field(description="CSS content")]
    media: Annotated[Optional[str], Field(description="CSS media query context (e.g., 'screen', 'print')")] = None


class ModuleType(Enum):
    esm = "esm"
    commonjs = "commonjs"
    script = "script"


class Assets43(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["javascript"]
    content: Annotated[str, Field(description="JavaScript content")]
    module_type: Annotated[Optional[ModuleType], Field(description="JavaScript module type")] = None


class VastVersion(Enum):
    field_2_0 = "2.0"
    field_3_0 = "3.0"
    field_4_0 = "4.0"
    field_4_1 = "4.1"
    field_4_2 = "4.2"


class TrackingEvent(Enum):
    start = "start"
    first_quartile = "firstQuartile"
    midpoint = "midpoint"
    third_quartile = "thirdQuartile"
    complete = "complete"
    impression = "impression"
    click = "click"
    pause = "pause"
    resume = "resume"
    skip = "skip"
    mute = "mute"
    unmute = "unmute"
    fullscreen = "fullscreen"
    exit_fullscreen = "exitFullscreen"
    player_expand = "playerExpand"
    player_collapse = "playerCollapse"


class Assets44(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["vast"]
    url: Annotated[AnyUrl, Field(description="URL endpoint that returns VAST XML")]
    content: Annotated[Optional[str], Field(description="Inline VAST XML content")] = None
    vast_version: Annotated[Optional[VastVersion], Field(description="VAST specification version")] = None
    vpaid_enabled: Annotated[
        Optional[bool], Field(description="Whether VPAID (Video Player-Ad Interface Definition) is supported")
    ] = None
    max_wrapper_depth: Annotated[
        Optional[int], Field(description="Maximum allowed wrapper/redirect depth", ge=0, le=10)
    ] = None
    duration_ms: Annotated[
        Optional[int], Field(description="Expected video duration in milliseconds (if known)", ge=0)
    ] = None
    tracking_events: Annotated[
        Optional[list[TrackingEvent]], Field(description="Tracking events supported by this VAST tag")
    ] = None


class Assets45(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["vast"]
    url: Annotated[Optional[AnyUrl], Field(description="URL endpoint that returns VAST XML")] = None
    content: Annotated[str, Field(description="Inline VAST XML content")]
    vast_version: Annotated[Optional[VastVersion], Field(description="VAST specification version")] = None
    vpaid_enabled: Annotated[
        Optional[bool], Field(description="Whether VPAID (Video Player-Ad Interface Definition) is supported")
    ] = None
    max_wrapper_depth: Annotated[
        Optional[int], Field(description="Maximum allowed wrapper/redirect depth", ge=0, le=10)
    ] = None
    duration_ms: Annotated[
        Optional[int], Field(description="Expected video duration in milliseconds (if known)", ge=0)
    ] = None
    tracking_events: Annotated[
        Optional[list[TrackingEvent]], Field(description="Tracking events supported by this VAST tag")
    ] = None


class DaastVersion(Enum):
    field_1_0 = "1.0"
    field_1_1 = "1.1"


class TrackingEvent14(Enum):
    start = "start"
    first_quartile = "firstQuartile"
    midpoint = "midpoint"
    third_quartile = "thirdQuartile"
    complete = "complete"
    impression = "impression"
    pause = "pause"
    resume = "resume"
    skip = "skip"
    mute = "mute"
    unmute = "unmute"


class Assets46(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["daast"]
    url: Annotated[AnyUrl, Field(description="URL endpoint that returns DAAST XML")]
    content: Annotated[Optional[str], Field(description="Inline DAAST XML content")] = None
    daast_version: Annotated[Optional[DaastVersion], Field(description="DAAST specification version")] = None
    duration_ms: Annotated[
        Optional[int], Field(description="Expected audio duration in milliseconds (if known)", ge=0)
    ] = None
    tracking_events: Annotated[
        Optional[list[TrackingEvent14]], Field(description="Tracking events supported by this DAAST tag")
    ] = None
    companion_ads: Annotated[Optional[bool], Field(description="Whether companion display ads are included")] = None


class Assets47(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["daast"]
    url: Annotated[Optional[AnyUrl], Field(description="URL endpoint that returns DAAST XML")] = None
    content: Annotated[str, Field(description="Inline DAAST XML content")]
    daast_version: Annotated[Optional[DaastVersion], Field(description="DAAST specification version")] = None
    duration_ms: Annotated[
        Optional[int], Field(description="Expected audio duration in milliseconds (if known)", ge=0)
    ] = None
    tracking_events: Annotated[
        Optional[list[TrackingEvent14]], Field(description="Tracking events supported by this DAAST tag")
    ] = None
    companion_ads: Annotated[Optional[bool], Field(description="Whether companion display ads are included")] = None


class Logo(BaseModel):
    url: Annotated[AnyUrl, Field(description="URL to the logo asset")]
    tags: Annotated[
        Optional[list[str]],
        Field(
            description="Semantic tags describing the logo variant (e.g., 'dark', 'light', 'square', 'horizontal', 'icon')"
        ),
    ] = None
    width: Annotated[Optional[int], Field(description="Logo width in pixels")] = None
    height: Annotated[Optional[int], Field(description="Logo height in pixels")] = None


class Colors(BaseModel):
    primary: Annotated[
        Optional[str], Field(description="Primary brand color (hex format)", pattern="^#[0-9A-Fa-f]{6}$")
    ] = None
    secondary: Annotated[
        Optional[str], Field(description="Secondary brand color (hex format)", pattern="^#[0-9A-Fa-f]{6}$")
    ] = None
    accent: Annotated[Optional[str], Field(description="Accent color (hex format)", pattern="^#[0-9A-Fa-f]{6}$")] = None
    background: Annotated[
        Optional[str], Field(description="Background color (hex format)", pattern="^#[0-9A-Fa-f]{6}$")
    ] = None
    text: Annotated[Optional[str], Field(description="Text color (hex format)", pattern="^#[0-9A-Fa-f]{6}$")] = None


class Fonts(BaseModel):
    primary: Annotated[Optional[str], Field(description="Primary font family name")] = None
    secondary: Annotated[Optional[str], Field(description="Secondary font family name")] = None
    font_urls: Annotated[Optional[list[AnyUrl]], Field(description="URLs to web font files if using custom fonts")] = (
        None
    )


class AssetType(Enum):
    image = "image"
    video = "video"
    audio = "audio"
    text = "text"


class Asset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_id: Annotated[str, Field(description="Unique identifier for this asset")]
    asset_type: Annotated[AssetType, Field(description="Type of asset")]
    url: Annotated[AnyUrl, Field(description="URL to CDN-hosted asset file")]
    tags: Annotated[
        Optional[list[str]],
        Field(description="Tags for asset discovery (e.g., 'holiday', 'lifestyle', 'product_shot')"),
    ] = None
    name: Annotated[Optional[str], Field(description="Human-readable asset name")] = None
    description: Annotated[Optional[str], Field(description="Asset description or usage notes")] = None
    width: Annotated[Optional[int], Field(description="Image/video width in pixels")] = None
    height: Annotated[Optional[int], Field(description="Image/video height in pixels")] = None
    duration_seconds: Annotated[Optional[float], Field(description="Video/audio duration in seconds")] = None
    file_size_bytes: Annotated[Optional[int], Field(description="File size in bytes")] = None
    format: Annotated[Optional[str], Field(description="File format (e.g., 'jpg', 'mp4', 'mp3')")] = None
    metadata: Annotated[Optional[dict[str, Any]], Field(description="Additional asset-specific metadata")] = None


class FeedFormat(Enum):
    google_merchant_center = "google_merchant_center"
    facebook_catalog = "facebook_catalog"
    custom = "custom"


class UpdateFrequency(Enum):
    realtime = "realtime"
    hourly = "hourly"
    daily = "daily"
    weekly = "weekly"


class ProductCatalog(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    feed_url: Annotated[AnyUrl, Field(description="URL to product catalog feed")]
    feed_format: Annotated[Optional[FeedFormat], Field(description="Format of the product feed")] = (
        "google_merchant_center"
    )
    categories: Annotated[
        Optional[list[str]], Field(description="Product categories available in the catalog (for filtering)")
    ] = None
    last_updated: Annotated[Optional[AwareDatetime], Field(description="When the product catalog was last updated")] = (
        None
    )
    update_frequency: Annotated[
        Optional[UpdateFrequency], Field(description="How frequently the product catalog is updated")
    ] = None


class Disclaimer(BaseModel):
    text: Annotated[str, Field(description="Disclaimer text")]
    context: Annotated[
        Optional[str],
        Field(description="When this disclaimer applies (e.g., 'financial_products', 'health_claims', 'all')"),
    ] = None
    required: Annotated[Optional[bool], Field(description="Whether this disclaimer must appear")] = True


class Contact(BaseModel):
    email: Annotated[Optional[EmailStr], Field(description="Contact email")] = None
    phone: Annotated[Optional[str], Field(description="Contact phone number")] = None


class Metadata(BaseModel):
    created_date: Annotated[Optional[AwareDatetime], Field(description="When this brand manifest was created")] = None
    updated_date: Annotated[Optional[AwareDatetime], Field(description="When this brand manifest was last updated")] = (
        None
    )
    version: Annotated[Optional[str], Field(description="Brand card version number")] = None


class BrandManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[
        AnyUrl,
        Field(
            description="Primary brand URL for context and asset discovery. Creative agents can infer brand information from this URL."
        ),
    ]
    name: Annotated[Optional[str], Field(description="Brand or business name")] = None
    logos: Annotated[
        Optional[list[Logo]], Field(description="Brand logo assets with semantic tags for different use cases")
    ] = None
    colors: Annotated[Optional[Colors], Field(description="Brand color palette")] = None
    fonts: Annotated[Optional[Fonts], Field(description="Brand typography guidelines")] = None
    tone: Annotated[
        Optional[str],
        Field(
            description="Brand voice and messaging tone (e.g., 'professional', 'casual', 'humorous', 'trustworthy', 'innovative')"
        ),
    ] = None
    tagline: Annotated[Optional[str], Field(description="Brand tagline or slogan")] = None
    assets: Annotated[
        Optional[list[Asset]],
        Field(
            description="Brand asset library with explicit assets and tags. Assets are referenced inline with URLs pointing to CDN-hosted files."
        ),
    ] = None
    product_catalog: Annotated[
        Optional[ProductCatalog],
        Field(
            description="Product catalog information for e-commerce advertisers. Enables SKU-level creative generation and product selection."
        ),
    ] = None
    disclaimers: Annotated[
        Optional[list[Disclaimer]],
        Field(description="Legal disclaimers or required text that must appear in creatives"),
    ] = None
    industry: Annotated[
        Optional[str], Field(description="Industry or vertical (e.g., 'retail', 'automotive', 'finance', 'healthcare')")
    ] = None
    target_audience: Annotated[Optional[str], Field(description="Primary target audience description")] = None
    contact: Annotated[Optional[Contact], Field(description="Brand contact information")] = None
    metadata: Annotated[Optional[Metadata], Field(description="Additional brand metadata")] = None


class Asset15(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_id: Annotated[str, Field(description="Unique identifier for this asset")]
    asset_type: Annotated[AssetType, Field(description="Type of asset")]
    url: Annotated[AnyUrl, Field(description="URL to CDN-hosted asset file")]
    tags: Annotated[
        Optional[list[str]],
        Field(description="Tags for asset discovery (e.g., 'holiday', 'lifestyle', 'product_shot')"),
    ] = None
    name: Annotated[Optional[str], Field(description="Human-readable asset name")] = None
    description: Annotated[Optional[str], Field(description="Asset description or usage notes")] = None
    width: Annotated[Optional[int], Field(description="Image/video width in pixels")] = None
    height: Annotated[Optional[int], Field(description="Image/video height in pixels")] = None
    duration_seconds: Annotated[Optional[float], Field(description="Video/audio duration in seconds")] = None
    file_size_bytes: Annotated[Optional[int], Field(description="File size in bytes")] = None
    format: Annotated[Optional[str], Field(description="File format (e.g., 'jpg', 'mp4', 'mp3')")] = None
    metadata: Annotated[Optional[dict[str, Any]], Field(description="Additional asset-specific metadata")] = None


class ProductCatalog13(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    feed_url: Annotated[AnyUrl, Field(description="URL to product catalog feed")]
    feed_format: Annotated[Optional[FeedFormat], Field(description="Format of the product feed")] = (
        "google_merchant_center"
    )
    categories: Annotated[
        Optional[list[str]], Field(description="Product categories available in the catalog (for filtering)")
    ] = None
    last_updated: Annotated[Optional[AwareDatetime], Field(description="When the product catalog was last updated")] = (
        None
    )
    update_frequency: Annotated[
        Optional[UpdateFrequency], Field(description="How frequently the product catalog is updated")
    ] = None


class BrandManifest12(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[
        Optional[AnyUrl],
        Field(
            description="Primary brand URL for context and asset discovery. Creative agents can infer brand information from this URL."
        ),
    ] = None
    name: Annotated[str, Field(description="Brand or business name")]
    logos: Annotated[
        Optional[list[Logo]], Field(description="Brand logo assets with semantic tags for different use cases")
    ] = None
    colors: Annotated[Optional[Colors], Field(description="Brand color palette")] = None
    fonts: Annotated[Optional[Fonts], Field(description="Brand typography guidelines")] = None
    tone: Annotated[
        Optional[str],
        Field(
            description="Brand voice and messaging tone (e.g., 'professional', 'casual', 'humorous', 'trustworthy', 'innovative')"
        ),
    ] = None
    tagline: Annotated[Optional[str], Field(description="Brand tagline or slogan")] = None
    assets: Annotated[
        Optional[list[Asset15]],
        Field(
            description="Brand asset library with explicit assets and tags. Assets are referenced inline with URLs pointing to CDN-hosted files."
        ),
    ] = None
    product_catalog: Annotated[
        Optional[ProductCatalog13],
        Field(
            description="Product catalog information for e-commerce advertisers. Enables SKU-level creative generation and product selection."
        ),
    ] = None
    disclaimers: Annotated[
        Optional[list[Disclaimer]],
        Field(description="Legal disclaimers or required text that must appear in creatives"),
    ] = None
    industry: Annotated[
        Optional[str], Field(description="Industry or vertical (e.g., 'retail', 'automotive', 'finance', 'healthcare')")
    ] = None
    target_audience: Annotated[Optional[str], Field(description="Primary target audience description")] = None
    contact: Annotated[Optional[Contact], Field(description="Brand contact information")] = None
    metadata: Annotated[Optional[Metadata], Field(description="Additional brand metadata")] = None


class ProductSelectors(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    manifest_skus: Annotated[
        Optional[list[str]], Field(description="Direct product SKU references from the brand manifest product catalog")
    ] = None
    manifest_tags: Annotated[
        Optional[list[str]],
        Field(
            description="Select products by tags from the brand manifest product catalog (e.g., 'organic', 'sauces', 'holiday')"
        ),
    ] = None
    manifest_category: Annotated[
        Optional[str],
        Field(
            description="Select products from a specific category in the brand manifest product catalog (e.g., 'beverages/soft-drinks', 'food/sauces')"
        ),
    ] = None
    manifest_query: Annotated[
        Optional[str],
        Field(
            description="Natural language query to select products from the brand manifest (e.g., 'all Kraft Heinz pasta sauces', 'organic products under $20')"
        ),
    ] = None


class Offering(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str, Field(description="Offering name (e.g., 'Winter Sale', 'New Product Launch')")]
    description: Annotated[Optional[str], Field(description="Description of what's being offered")] = None
    assets: Annotated[Optional[list[dict[str, Any]]], Field(description="Assets specific to this offering")] = None


class AssetType22(Enum):
    image = "image"
    video = "video"
    audio = "audio"
    vast = "vast"
    daast = "daast"
    text = "text"
    url = "url"
    html = "html"
    css = "css"
    javascript = "javascript"
    webhook = "webhook"


class AssetSelectors(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tags: Annotated[
        Optional[list[str]], Field(description="Select assets with specific tags (e.g., ['holiday', 'premium'])")
    ] = None
    asset_types: Annotated[
        Optional[list[AssetType22]], Field(description="Filter by asset type (e.g., ['image', 'video'])")
    ] = None
    exclude_tags: Annotated[Optional[list[str]], Field(description="Exclude assets with these tags")] = None


class Assets48(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    brand_manifest: Annotated[
        Union[Union[BrandManifest, BrandManifest12], AnyUrl],
        Field(
            description="Brand manifest provided either as an inline object or a URL string pointing to a hosted manifest",
            examples=[
                {
                    "description": "Inline brand manifest",
                    "data": {
                        "url": "https://acmecorp.com",
                        "name": "ACME Corporation",
                        "colors": {"primary": "#FF6B35"},
                    },
                },
                {
                    "description": "URL string reference to hosted manifest",
                    "data": "https://cdn.acmecorp.com/brand-manifest.json",
                },
            ],
            title="Brand Manifest Reference",
        ),
    ]
    product_selectors: Annotated[
        Optional[ProductSelectors],
        Field(
            description="Specification of products or offerings being promoted in a campaign. Supports multiple selection methods from the brand manifest that can be combined using UNION (OR) logic. When multiple selection methods are provided, products matching ANY of the criteria are selected (logical OR, not AND).",
            examples=[
                {
                    "description": "Direct SKU selection for specific products from brand manifest",
                    "data": {"manifest_skus": ["SKU-12345", "SKU-67890"]},
                },
                {
                    "description": "UNION selection: products tagged 'organic' OR 'sauces' OR in 'food/condiments' category from brand manifest",
                    "data": {"manifest_tags": ["organic", "sauces"], "manifest_category": "food/condiments"},
                },
                {
                    "description": "Natural language product selection from brand manifest",
                    "data": {"manifest_query": "all Kraft Heinz pasta sauces under $5"},
                },
                {"description": "Select products by tags", "data": {"manifest_tags": ["holiday"]}},
            ],
            title="Promoted Products",
        ),
    ] = None
    offerings: Annotated[
        Optional[list[Offering]],
        Field(
            description="Inline offerings for campaigns without a product catalog. Each offering has a name, description, and associated assets."
        ),
    ] = None
    asset_selectors: Annotated[
        Optional[AssetSelectors], Field(description="Selectors to choose specific assets from the brand manifest")
    ] = None


class Assets49(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["url"]
    url: Annotated[AnyUrl, Field(description="URL reference")]
    description: Annotated[Optional[str], Field(description="Description of what this URL points to")] = None


class Status8(Enum):
    active = "active"
    paused = "paused"
    ended = "ended"


class AssignedPackage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    package_id: Annotated[str, Field(description="Package identifier")]
    package_name: Annotated[Optional[str], Field(description="Human-readable package name")] = None
    assigned_date: Annotated[AwareDatetime, Field(description="When this assignment was created")]
    status: Annotated[Status8, Field(description="Status of this specific assignment")]


class Assignments(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    assignment_count: Annotated[int, Field(description="Total number of active package assignments", ge=0)]
    assigned_packages: Annotated[
        Optional[list[AssignedPackage]], Field(description="List of packages this creative is assigned to")
    ] = None


class Performance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    impressions: Annotated[Optional[int], Field(description="Total impressions across all assignments", ge=0)] = None
    clicks: Annotated[Optional[int], Field(description="Total clicks across all assignments", ge=0)] = None
    ctr: Annotated[Optional[float], Field(description="Click-through rate (clicks/impressions)", ge=0.0, le=1.0)] = None
    conversion_rate: Annotated[
        Optional[float], Field(description="Conversion rate across all assignments", ge=0.0, le=1.0)
    ] = None
    performance_score: Annotated[
        Optional[float], Field(description="Aggregated performance score (0-100)", ge=0.0, le=100.0)
    ] = None
    last_updated: Annotated[AwareDatetime, Field(description="When performance data was last updated")]


class SubAssets(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Annotated[
        str,
        Field(
            description="Type of asset. Common types: headline, body_text, thumbnail_image, product_image, featured_image, logo, cta_text, price_text, sponsor_name, author_name, click_url"
        ),
    ]
    asset_id: Annotated[str, Field(description="Unique identifier for the asset within the creative")]
    content_uri: Annotated[AnyUrl, Field(description="URL for media assets (images, videos, etc.)")]
    content: Annotated[
        Optional[Union[str, list[str]]],
        Field(description="Text content for text-based assets like headlines, body text, CTA text, etc."),
    ] = None


class SubAssets1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Annotated[
        str,
        Field(
            description="Type of asset. Common types: headline, body_text, thumbnail_image, product_image, featured_image, logo, cta_text, price_text, sponsor_name, author_name, click_url"
        ),
    ]
    asset_id: Annotated[str, Field(description="Unique identifier for the asset within the creative")]
    content_uri: Annotated[Optional[AnyUrl], Field(description="URL for media assets (images, videos, etc.)")] = None
    content: Annotated[
        Union[str, list[str]],
        Field(description="Text content for text-based assets like headlines, body text, CTA text, etc."),
    ]


class Creative(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    creative_id: Annotated[str, Field(description="Unique identifier for the creative")]
    name: Annotated[str, Field(description="Human-readable creative name")]
    format_id: Annotated[
        FormatId, Field(description="Structured format identifier with agent URL and format name", title="Format ID")
    ]
    status: Annotated[Status, Field(description="Status of a creative asset", title="Creative Status")]
    created_date: Annotated[AwareDatetime, Field(description="When the creative was uploaded to the library")]
    updated_date: Annotated[AwareDatetime, Field(description="When the creative was last modified")]
    media_url: Annotated[Optional[AnyUrl], Field(description="URL of the creative file (for hosted assets)")] = None
    assets: Annotated[
        Optional[
            dict[
                str,
                Union[
                    Assets,
                    Assets38,
                    Assets39,
                    Assets40,
                    Assets41,
                    Assets42,
                    Assets43,
                    Union[Assets44, Assets45],
                    Union[Assets46, Assets47],
                    Assets48,
                    Assets49,
                ],
            ]
        ],
        Field(description="Assets for this creative, keyed by asset_role"),
    ] = None
    click_url: Annotated[Optional[AnyUrl], Field(description="Landing page URL for the creative")] = None
    duration: Annotated[Optional[float], Field(description="Duration in milliseconds (for video/audio)", ge=0.0)] = None
    width: Annotated[Optional[float], Field(description="Width in pixels (for video/display)", ge=0.0)] = None
    height: Annotated[Optional[float], Field(description="Height in pixels (for video/display)", ge=0.0)] = None
    tags: Annotated[Optional[list[str]], Field(description="User-defined tags for organization and searchability")] = (
        None
    )
    assignments: Annotated[
        Optional[Assignments], Field(description="Current package assignments (included when include_assignments=true)")
    ] = None
    performance: Annotated[
        Optional[Performance],
        Field(description="Aggregated performance metrics (included when include_performance=true)"),
    ] = None
    sub_assets: Annotated[
        Optional[list[Union[SubAssets, SubAssets1]]],
        Field(description="Sub-assets for multi-asset formats (included when include_sub_assets=true)"),
    ] = None


class StatusSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    approved: Annotated[Optional[int], Field(description="Number of approved creatives", ge=0)] = None
    pending_review: Annotated[Optional[int], Field(description="Number of creatives pending review", ge=0)] = None
    rejected: Annotated[Optional[int], Field(description="Number of rejected creatives", ge=0)] = None
    archived: Annotated[Optional[int], Field(description="Number of archived creatives", ge=0)] = None


class ListCreativesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    query_summary: Annotated[QuerySummary, Field(description="Summary of the query that was executed")]
    pagination: Annotated[Pagination, Field(description="Pagination information for navigating results")]
    creatives: Annotated[list[Creative], Field(description="Array of creative assets matching the query")]
    format_summary: Annotated[Optional[dict[str, int]], Field(description="Breakdown of creatives by format type")] = (
        None
    )
    status_summary: Annotated[Optional[StatusSummary], Field(description="Breakdown of creatives by status")] = None
