# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_list-authorized-properties-request_json.json
#   source_etag: W/"68ee6f3c-288"
#   source_last_modified: Tue, 14 Oct 2025 15:41:48 GMT

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Tag(RootModel[str]):
    root: Annotated[
        str, Field(description="Tag to filter by (e.g., 'local_radio', 'premium_content')", pattern="^[a-z0-9_]+$")
    ]


class ListAuthorizedPropertiesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tags: Annotated[Optional[list[Tag]], Field(description="Filter properties by specific tags (optional)")] = None
