# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_creative-status_json.json
#   schema_hash: a8fb5f8602b7

from __future__ import annotations

from enum import Enum


class CreativeStatus(Enum):
    processing = "processing"
    approved = "approved"
    rejected = "rejected"
    pending_review = "pending_review"
