# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_creative-status_json.json
#   source_etag: W/"68ee6f3c-237"
#   source_last_modified: Tue, 14 Oct 2025 15:41:48 GMT

from __future__ import annotations

from enum import Enum


class CreativeStatus(Enum):
    processing = "processing"
    approved = "approved"
    rejected = "rejected"
    pending_review = "pending_review"
